"""team needs and tech tags tables

Revision ID: 1b458dcab7ad
Revises: a25dc4bf20ee
Create Date: 2025-11-11 17:38:38.379764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b458dcab7ad'
down_revision: Union[str, Sequence[str], None] = 'a25dc4bf20ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', postgresql.ENUM('LANGUAGE', 'FRAMEWORK', 'TOOL', name='techtagkind'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tech_tags_kind'), 'tech_tags', ['kind'], unique=False)
    op.create_table('team_needs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('direction', postgresql.ENUM('BACKEND', 'FRONTEND', 'MOBILE', 'MLOPS', name='direction'), nullable=False),
    sa.Column('required_level', postgresql.ENUM('JUNIOR', 'MIDDLE', 'SENIOR', name='experiencelevel'), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_need_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', postgresql.ENUM('MUST', 'NICE', name='needrequirementtype'), nullable=False),
    sa.Column('need_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['need_id'], ['team_needs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tech_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_need_tags')
    op.drop_table('team_needs')
    op.drop_index(op.f('ix_tech_tags_kind'), table_name='tech_tags')
    op.drop_table('tech_tags')
    # ### end Alembic commands ###
