"""introduce team memberships table

Revision ID: 359498aac64f
Revises: bfe36dc0a275
Create Date: 2025-11-07 05:29:49.396841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '359498aac64f'
down_revision: Union[str, Sequence[str], None] = 'bfe36dc0a275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', name='teamrole'), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('unique_team_owner_idx', 'team_memberships', ['team_id'], unique=True, postgresql_where=sa.text("role = 'OWNER'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_team_owner_idx', table_name='team_memberships', postgresql_where=sa.text("role = 'OWNER'"))
    op.drop_table('team_memberships')
    # ### end Alembic commands ###
