"""add trigram indeces to tech tags

Revision ID: 56a10f6e3e50
Revises: 67a6d16d7bee
Create Date: 2025-11-18 20:27:13.952153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a10f6e3e50'
down_revision: Union[str, Sequence[str], None] = '67a6d16d7bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tech_tags_name_trgm', 'tech_tags', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('tech_tags_slug_trgm', 'tech_tags', ['slug'], unique=False, postgresql_using='gin', postgresql_ops={'slug': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tech_tags_slug_trgm', table_name='tech_tags', postgresql_using='gin', postgresql_ops={'slug': 'gin_trgm_ops'})
    op.drop_index('tech_tags_name_trgm', table_name='tech_tags', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
