"""create profile related tables

Revision ID: 6324c924345c
Revises: 56a10f6e3e50
Create Date: 2025-11-19 19:35:55.131975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6324c924345c'
down_revision: Union[str, Sequence[str], None] = '56a10f6e3e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', postgresql.ENUM('BACKEND', 'FRONTEND', 'MOBILE', 'MLOPS', name='direction', create_type=False), nullable=False),
    sa.Column('experience_level', postgresql.ENUM('JUNIOR', 'MIDDLE', 'SENIOR', name='experiencelevel', create_type=False), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('achievements', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', name='profilevisibility'), nullable=False),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_direction'), 'profiles', ['direction'], unique=False)
    op.create_index(op.f('ix_profiles_visibility'), 'profiles', ['visibility'], unique=False)
    op.create_table('profile_tech_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('tech_tag_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level BETWEEN 1 AND 5', name='profile_tech_tags_level_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_tag_id'], ['tech_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'tech_tag_id', name='profile_tech_tags_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_tech_tags')
    op.drop_index(op.f('ix_profiles_visibility'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_direction'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
