"""remove bio and profile pic url from users table (will be transferred to profiles table)

Revision ID: 94f2f478bab5
Revises: 1b458dcab7ad
Create Date: 2025-11-12 15:23:30.509013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f2f478bab5'
down_revision: Union[str, Sequence[str], None] = '1b458dcab7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
