"""introduce team requests tables

Revision ID: a25dc4bf20ee
Revises: 359498aac64f
Create Date: 2025-11-07 15:36:32.560855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a25dc4bf20ee'
down_revision: Union[str, Sequence[str], None] = '359498aac64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELED', name='teamapplicationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('team_applications_unique_pending_idx', 'team_applications', ['team_id', 'applicant_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('team_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('invited_user_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELED', name='teaminvitestatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('team_invites_unique_pending_idx', 'team_invites', ['team_id', 'invited_user_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    
    teammembershiporigin_enum = postgresql.ENUM('INVITE', 'APPLICATION', 'SYSTEM', name='teammembershiporigin', create_type=False)
    teammembershiporigin_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('team_memberships', sa.Column('origin', teammembershiporigin_enum, nullable=False))
    
    op.add_column('team_memberships', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('team_memberships', sa.Column('source_invite_id', sa.Uuid(), nullable=True))
    op.add_column('team_memberships', sa.Column('source_application_id', sa.Uuid(), nullable=True))
    op.add_column('team_memberships', sa.Column('added_by_user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint('team_memberships_source_application_id_unique', 'team_memberships', ['source_application_id'])
    op.create_unique_constraint('team_memberships_source_invite_id_unique', 'team_memberships', ['source_invite_id'])
    op.drop_constraint(op.f('team_memberships_invited_by_fkey'), 'team_memberships', type_='foreignkey')
    op.create_foreign_key('team_memberships_added_by_user_id_fkey', 'team_memberships', 'users', ['added_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('team_memberships_source_application_id_fkey', 'team_memberships', 'team_applications', ['source_application_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('team_memberships_source_invite_id_fkey', 'team_memberships', 'team_invites', ['source_invite_id'], ['id'], ondelete='SET NULL')
    op.drop_column('team_memberships', 'invited_by')
    op.drop_column('team_memberships', 'invited_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_memberships', sa.Column('invited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('team_memberships', sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('team_memberships_added_by_user_id_fkey', 'team_memberships', type_='foreignkey')
    op.drop_constraint('team_memberships_source_application_id_fkey', 'team_memberships', type_='foreignkey')
    op.drop_constraint('team_memberships_source_invite_id_fkey', 'team_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('team_memberships_invited_by_fkey'), 'team_memberships', 'users', ['invited_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint('team_memberships_source_application_id_unique', 'team_memberships', type_='unique')
    op.drop_constraint('team_memberships_source_invite_id_unique', 'team_memberships', type_='unique')
    op.drop_column('team_memberships', 'added_by_user_id')
    op.drop_column('team_memberships', 'source_application_id')
    op.drop_column('team_memberships', 'source_invite_id')
    op.drop_column('team_memberships', 'joined_at')
    op.drop_column('team_memberships', 'origin')
    op.drop_index('team_invites_unique_pending_idx', table_name='team_invites', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('team_invites')
    op.drop_index('team_applications_unique_pending_idx', table_name='team_applications', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('team_applications')
    # ### end Alembic commands ###
