"""introduce teams table

Revision ID: bfe36dc0a275
Revises: a629654c84b7
Create Date: 2025-11-07 04:15:24.828161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfe36dc0a275'
down_revision: Union[str, Sequence[str], None] = 'a629654c84b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('current_members', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'RECRUITING', 'FULL', 'CLOSED', name='teamstatus'), nullable=False),
    sa.Column('visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', name='teamvisibility'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_members >= current_members AND max_members > 0 AND max_members <= 5', name='max_members_check'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
